services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: tlg_gamebot
    container_name: tlg_gamebot
    env_file:
      - .env
    volumes:
      - ./logs.txt:/app/logs.txt
      - ./database.db:/app/database.db
    restart: unless-stopped